# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm ci
      - name: Run TU
        run: npm run test:coverage
      - name: Run lint
        run: npm run lint

      - name: Publish TU Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests                  # Name of the check run which will be created
          path: reports/jest-junit.xml      # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results

    
